#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
configuration: Release

build:
  project: Ptv-CITest.sln        # path to Visual Studio solution or project
  publish_wap: false              # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false        # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false            # package Azure Cloud Service projects and push to artifacts
  publish_nuget: false            # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  verbosity: detailed              # quiet|minimal|normal|detailed

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

# to disable automatic builds
#build: off